### ISSUE TITLE
FEAT: Supportability metadata "breadcrumbs"

### ISSUE THREAD

**Issue by abenokraitis** [ansible/galaxy-dev#103]
Would be great to have offline supportability claims built into Collections on Galaxy and/or the collection itself. Granted, the collection could be in both Galaxy and Automation Hub, but users and support engineers will need to know where and how the collection was downloaded and installed for support claims.

**Comment by chouseknecht** [comment]
How will one 'build in supportabilty claims' to a Collection? Need more detail. This sorta sounds like a metadata thing that needs to be added to the Collection spec, maybe.

**Comment by abenokraitis** [comment]
Thinking out loud, let's assume a Collection was installed by someone, but someone else is in charge of using it. This person has no idea where or how the Collection was installed, and would need some kind of means to determine the source of the download and install for troubleshooting.

**Comment by chouseknecht** [comment]
A signing feature is being added to the backend so that when a Collection is published to AH, it will get signed. The `ansible-galaxy` client will then be able to look for this signature and report whether or not the Collection was installed from AH.

This is the first step to solving this. There may be other things we want to bake into Collections coming from AH with regards to support docs or verbiage.

**Comment by chouseknecht** [comment]
Assigning the client side to @alikins

**Comment by chouseknecht** [comment]
Requirements

- Ability to validate from where content was downloaded
- Enable customer to limit from where content can be installed
- Enable customer to limit which content can be executed in a given environment (i.e., only run content provided by Red Hat and partner X).

**Comment by chouseknecht** [comment]
Based on conversation with Richard and Brian, content signing doesn't really solve the above use cases. Punting for a future release.

**Comment by chouseknecht** [comment]
Signing is back. See #183
