### ISSUE TITLE
Collection import mysteriously canceled

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy-dev#106]
I tried uploading this collection: https://github.com/ansible/ansible_collections_google to automation hub, and the import was automatically canceled after a little bit.

Import status: 
https://ci.cloud.redhat.com/api/automation-hub/v3/_ui/imports/collections/?namespace=google

Import log:
https://ci.cloud.redhat.com/api/automation-hub/v3/_ui/imports/collections/027dab31-eb86-4acd-942f-410aa8d440aa/

My theory is that the collection is so big, it's timing out.

**Comment by romanblanco** [comment]
@newswangerd, this does not seem to be an issue anymore.

I've tested this in both my local environment and the CI environment and the collection upload works for me.

Closing.
