### ISSUE TITLE
Filing of features and defects against Collections should be super easy (follow the source)

### ISSUE THREAD

**Issue by abenokraitis** [ansible/galaxy-dev#108]
With the move to Collections, as well as most content moving out of the Ansible GitHub organization, it will be extremely confusing for users to file issues when they don't know where the source actually exists. This request adds additional functionality in Galaxy to quickly file an issue. As it relates to Automation Hub, this should already be known and used by Red Hat Support to file issues (hopefully) if this feature is also added there as well.

**Comment by chouseknecht** [comment]
Not sure where you are wanting users to file issues. Building an issue tricker into AH is likely not the right thing. Agree, there should be some link and instructions to the right place to file issues and get help.

**Comment by abenokraitis** [comment]
Yeah, thinking about this more, given a post to Galaxy and a post to Automation Hub are two discrete activities, and assuming two different data stores, the pointer to the "source" could be different in fact. I would also assume filing issues would be much more important on the Galaxy side since certified/supported content in Automation Hub would go through Support. Regardless, Support probably still needs a way to file issues as well and tag them as escalated.

**Comment by chouseknecht** [comment]
If we're given in the collection metadata links to source repo and issue tracker, we display those in the AH UI today. It's up to the partner to provide these items, but they're not currently required.
