### ISSUE TITLE
Importer: Run ansible-test via container

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy-dev#122]
Decide if we want to use a container for the import process

- Why potentially use a container in the import process:
  - Have all relevant python versions installed for `ansible-test` (currently importer only calls `ansible-test sanity` with 1 python version)
  - Resolve any environment differences we may get from extracting and running `ansible-test sanity` locally
  - Improve `ansible-test` sandboxing (replace bubblewrap)
- Likely container would be based on the one used by `ansible-test sanity`
- Need to ensure within openshift we can have a container spin up a sibling container
- Option: Run the whole importer inside it’s own container
  - Note: Importer is not called just within galaxy-dev AH environment, it is called by `pulp_ansible` so that non-galaxy use case needs to be supported. We also need to maintain running standalone via `galaxy_importer.main`
- Option: Within the importer portion that calls `ansible-test` (`hub-importer-plugin`), use a container to run just `ansible-test` inside it’s own container
  - Note: `pulp_ansible` does not use `hub-importer-plugin` so this approach would not impact `pulp_ansible`

**Comment by chouseknecht** [comment]
On OpenShift we're going to:

1. Use the OpenShift API to build an image with `ansible-test` and the Collection
2. Execute the image with no outbound network access
3. Capture the output

**Comment by chouseknecht** [comment]
Deployed to ansible-test to production.
