### ISSUE TITLE
Infra: black-box alerting and slack config

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-dev#130]
For go-live we need:

- [ ] A simple HTTP monitor setup in the Insights' Prometheus instance. It will check for a 200 response from the automation hub partner page every 30 seconds. If it gets something other than a 200 over a 5 minute period, then it will send an alert to Pager Duty. 

- [ ] ~~The team will be configured in pager duty. Probably to start with @cutwater and @chouseknecht should be alerted via text messages and phone calls.~~ Ideally we should have pager duty alert us in Slack too, if possible, so that others on the team can jump in.

**Comment by chouseknecht** [comment]
Contact for this is Christopher Moore.
Getting started doc from the SRE team: http://platform-docs.cloud.paas.psi.redhat.com/sre/metrics/index.html

**Comment by alikins** [comment]
Taking a look at this.

**Comment by chouseknecht** [comment]
I think in a previous conversation we said we would start with notifications going to Slack and add Pagerduty alerting later.
