### ISSUE TITLE
Importer: Make a separate virtualenv for ansible-test to use

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy-dev#147]
We want the venv on the container to be read-only

When using `ansible-test sanity` with  `--local` it uses the container’s venv. While it does not install new packages with `--local`, it does write inside venv by creating `/ansible.egg-info/PKG_INFO` under the venv under `site-packages`

To resolve we will add a separate virtualenv as a docker volume for ansible-test to use

**Comment by chouseknecht** [comment]
Believe this is fixed. Needs CI deployment and verification testing.

**Comment by awcrosby** [comment]
No longer applicable with using ansible-test within it's own container #122
