### ISSUE TITLE
CI cannot accept new collections

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy-dev#164]
Attempts to publish a new collection artifact fail to spawn an import task on CI.

Worked on this with @cutwater earlier, when he determined the pulp workers appear to be marked incorrectly causing tasks to get sent to incorrect or invalid workers (I am not sure which was the case).

This hinders tests, and whatever caused it needs corrected so that 1) future deploys don't cause the same mis-marking and 2) deploys to prod don't create the same problem.

**Comment by chouseknecht** [comment]
Fixed.
