### ISSUE TITLE
Importer: Accept same collection version when existing version state is 'rejected'

### ISSUE THREAD

**Issue by anshulbehl** [ansible/galaxy-dev#189]
Hi Team,

Currently, when PE team rejects to certify a collection the partner/user cannot upload the same version again as according to AH the artifact is already present.
This should change and a rejected version should be "soft-removed" in order to allow the same version to be uploaded again.

Reason: Partners may be following a versioning scheme and would probably not want our certification  workflow affecting that, or this also can force product team who want product and collection versions to be the same to change collection version.

cc: @thedoubl3j

**Comment by thedoubl3j** [comment]
We have encountered this a couple of times with partners as well with internal teams. 

The idea here is that if a collection was rejected in the certification dashboard view, then the same version of the collection should be able to be uploaded as the first one was never "truly" published.

**Comment by chouseknecht** [comment]
Modify the import process to be aware of the state of an existing collection version. If the state is 'rejected', the `pulp-ansible` importer will delete the existing collection version, allowing the AH importer to import the new artifact as the same version.

**Comment by alikins** [comment]
I think supporting deleting collection versions is the wrong approach for this requirement[1].

For this particular case, a different approach would be to never create a CollectionVesion until the import and review process is done. So a collection version artifact import that fails or is rejected upon review, should never create a CollectionVersion entry.

Though, not creating an official CollectionVersion in the default pulp Repository (automation-hub)
and adding content promotion/review workflows that will allow it to be promoted to a "real" CollectionVersion is described in other issues. ie

- https://github.com/ansible/galaxy-dev/issues/217
- https://github.com/ansible/galaxy-dev/issues/208
- https://github.com/ansible/galaxy-dev/issues/210
- https://github.com/ansible/galaxy-dev/issues/211
- https://github.com/ansible/galaxy-dev/issues/212
- https://github.com/ansible/galaxy-dev/issues/215
- 


[1] supporting collection versions deletion may be useful for other reasons however.

**Comment by chouseknecht** [comment]
@alikins 

The idea of 'not creating a collection version' sounds like a good one. However, I don't think it's practical. Upon import the artifact and the import logs have to be stored somewhere so that they can be surface in the future for review by the partner engineering team.

We could store them in a separate repository, which is discussed in the issues you've linked to. However, we would still have the same problem to solve: when an artifact is rejected by the partner engineering team, the partner will want to fix the problem and upload a new version of the artifact. We would still need to remove and replace the rejected artifact from a repository.

**Comment by chouseknecht** [comment]
Blocked by the following: 

- [ ] pulp_galaxy plugin
- [ ] introduction of repositories, such that there are separate repositories for 'uncertified' and 'certified' content.

**Comment by bmclaughlin** [comment]
Currently the Buildah dependencies (requires `container_selinux`) are conflicting with the build instructions (exclude `container_selinux`) which needs resolution.  Being tracked here [1].

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1806044

**Comment by chouseknecht** [comment]
Migrated to galaxy_ng and the 4.2 milestone.
