### ISSUE TITLE
Story: Sandboxing the importer

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-dev#194]
Problem: 
- [ ] Isolate the custom Collection code during static analysis and `ansible-test`, such that there can be no root access and no outbound network connections
- [ ] Execute on OpenShift and a standalone VM
- [ ] be able to inject custom configuration for any lint and test tools

**Comment by chouseknecht** [comment]
#122 - @awcrosby 

@bmbouters will be working on the following:

Investigate with the [pulp_container team](https://github.com/pulp/pulp_container) to add functionality for building an image from a Dockerfile. We're told the pieces for executing a build are mostly there, and image build is on the roadmap.

**Comment by chouseknecht** [comment]
#222 is part of this story. Once we're able to run `ansible-test` and capture the output, we need to surface it in the UI. It will automatically show up on My Imports, but it needs to be added to Content Details for a given collection version.

**Comment by awcrosby** [comment]
ansible-test sanity is now deployed on production, running in separate jobs in a separate service set.
