### ISSUE TITLE
OpenAPI Doc Creation

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-dev#2]
Create an OpenAPI doc that represents the new API. We're creating v3 of the API. @cutwater has documented the needed endpoints here: https://docs.google.com/document/d/1gbK68R7CrmQVNkHBvG9-glwM_hJFUyPExA2RTNEdziI/edit

**Comment by alikins** [comment]
https://github.com/ansible/galaxy-api/blob/master/openapi/openapi.yaml

A current pr for comments:
https://github.com/ansible/galaxy-api/pull/8

**Comment by alikins** [comment]
https://github.com/ansible/galaxy-api/pull/8 should match https://docs.google.com/document/d/1gbK68R7CrmQVNkHBvG9-glwM_hJFUyPExA2RTNEdziI/edit as of now

Viewable at 
Viewable at https://petstore.swagger.io/?url=https://raw.githubusercontent.com/alikins/galaxy-api/openapi_collection_imports/openapi/openapi.yaml

**Comment by cutwater** [comment]
Closed in favor of #29
