### ISSUE TITLE
UI: Add download button

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-dev#239]
We have users on air-gapped networks that would like to obtain a copy of the collection artifact and distribute copies within their org. Currently the CLI deletes the artifact upon install.

**Comment by chouseknecht** [comment]
Corresponding issue on community galaxy: https://github.com/ansible/galaxy/issues/2198

**Comment by newswangerd** [comment]
Right now downloaded filenames are a random string of characters. I've added the download button, but it's not very useful until we fix the filename issue, which is going to require adding support for the `Content-Disposition` header in Pulp.

**Comment by newswangerd** [comment]
`Content-Disposition` pulp issue: https://pulp.plan.io/issues/4733

**Comment by chouseknecht** [comment]
We're still missing the file extension in the `Content-Distribution` header received from Pulp.

**Comment by chouseknecht** [comment]
Testing in CI. Moved to galaxy_ng repository.
