### ISSUE TITLE
Artifact Upload: invalid filenames cause 500 without error message

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy-dev#244]
##### SUMMARY
When uploading artifacts to the V3 upload endpoint and uploading a filename that does not match the prescribed `namespace-name-version.tar.gz` pattern, a 500 response is returned indicating an unhandled internal error and no proper reporting of the issue.

##### STEPS TO REPRODUCE
- Build a collection artifact
- Rename the resulting artifact
- Upload it to Automation Hub

##### EXPECTED RESULTS

An error about the filename indicating the problem, as it cannot be matched with its expected namespace
*OR*
The namespace, name, and version to be used from the metadata and the filename ignored.

Note: please clarify the intended result and follow up with QE.

##### ACTUAL RESULTS
500 Internal Server Error and no clear information

**Comment by alikins** [comment]
Fixed by 980728f79e56d2a08dd673389944d18c7afb83af

Now returns a 400 error with info about the filename and the error, and logs that info as well.

![screenshot_example_bad_filename](https://user-images.githubusercontent.com/15162/74346686-ed8e5400-4d7d-11ea-84e5-461d43e0f0b2.png)

**Comment by ironfroggy** [comment]
Test passes 👍
