### ISSUE TITLE
Infra: Install pulp_container plugin

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-dev#254]
Install [pulp_container](https://github.com/pulp/pulp_container) plugin so that we can have a consistent way to build images both on and off OSD. In the future, pulp_container also allows us to offer an image registry service to PAH users.

**Comment by chouseknecht** [comment]
Probably needs to be add here:  https://github.com/ansible/galaxy-dev/blob/master/docker/pulp/Dockerfile, since that's where we install pulp_ansible and other Pulp bits. Verify with @cutwater.

Check with @daviddavis and/or @bmbouter for the version of pulp_container.

**Comment by daviddavis** [comment]
FYI, @dkliban might also be able to help determine the version of pulp_container needed.

**Comment by dkliban** [comment]
pulp_container 1.1.0 has the feature needed. https://pypi.org/project/pulp-container/1.1.0/

**Comment by chouseknecht** [comment]
Replaced by #288
