### ISSUE TITLE
PagerDuty Alerts

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-dev#281]
Now that we have PagerDuty access, we need to do the following:

- [ ] For Community Galaxy, migrate from CopperEgg to Prometheus for monitoring. There is monitoring configured in Prometheus today. Need to review what's there, make sure it includes basic health checks, and point those alerts to PagerDuty. 
- [ ] For Automation Hub we have Prometheus configured and pointed to Slack. In addition to Slack, point basic health checks to PagerDuty.

**Comment by alikins** [comment]
https://github.com/RedHatInsights/e2e-deploy/pull/1162 
Fixes "For Automation Hub we have Prometheus configured and pointed to Slack. In addition to Slack, point basic health checks to PagerDuty."
