### ISSUE TITLE
API: Define Collection Import schemas

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy-dev#35]
Define schemas that describe Collection Import and relevant objects,
request and response formats.

**Comment by chouseknecht** [comment]
Add the following example schemas to the `_ui` API path:
- https://galaxy.ansible.com/api/internal/ui/namespaces/2901/imports/
- https://galaxy.ansible.com/api/v2/collection-imports/104/

Remove the Lint records, those will not be applicable for Automation Hub.

**Comment by alikins** [comment]
@cutwater @chouseknecht @newswangerd 

For collection-imports, the client (ansible-galaxy) will be using the API endpoint as well. So
there should probably be a non-/_ui endpoint for collection imports. (It polls and waits for an import to be finished by following the link from the POST /collection return)

So probably a `/imports/collections/{import_id}` or `/collection-imports/{import_id}` on the "public" API that implements a `/api/v2/collection-imports/{import_id}` like interface.

And then a ui/internal clone of `/api/internal/ui/namespaces/{namespace_id}/imports` 
at `/_ui/namespaces/{namespace_id}/imports`  ?

**Comment by cutwater** [comment]
@alikins Personally I prefer `/imports/collections/{import_id}` for public one.
Let's use similar URL scheme for ui URLs as well, so it'd bee:

```
/_ui/imports/collections?namespace=foo
/_ui/imports/collections/{import_id}
```

**Comment by alikins** [comment]
@cutwater 

```
/_ui/imports/collections?namespace=foo
/_ui/imports/collections/{import_id}
```

Works for me.
