### ISSUE TITLE
API: For Collections, update the Public schema and add a _ui schema

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-dev#55]
In general the v3 or public API schema will look https://galaxy.ansible.com/api/v2/collections/. The main thing we need to do in this task is verify that the v3 Collections endpoints return the response object expected by the `ansible-galaxy` client.

Remove the `/search/collections` endpoint.

Add an internal schema for getting a list of Collections. It will look like: https://galaxy.ansible.com/api/internal/ui/collections/

Add an internal schema for getting a specific Collection's detail. It will look like: https://galaxy.ansible.com/api/internal/ui/collections/newswangerd/collection_demo/

Add an internal schema for getting information about a collection version that returns the same level of information returned in the `latest_version` keyword in https://galaxy.ansible.com/api/internal/ui/collections/newswangerd/collection_demo/

For the internal schemas: 

- [x] Add a `_ui` path to the API
- [x] Add the collection endpoints
- [x] Make the response objects match the above example endpoints
  - [x] For /collections/
  - [x] For /_ui/collections/
     - [x] For /_ui/collections/
     - [x] For /_ui/collections/{namespace}/{name}
- [ ] Add the search parameters from Community Galaxy that apply to Collections. Exclude `platforms`, `clode_platforms` and `contributor type`.
- [x] Review with @newswangerd

**Comment by alikins** [comment]
@chouseknecht "The main thing we need to do in this task is verify that the v3 Collections endpoints return the response object expected by the ansible-galaxy client."

Aside from the pagination and error handling which needs to be insights style correct?

**Comment by alikins** [comment]
@chouseknecht  "Add the search parameters from Community Galaxy that apply to Collections. Exclude platforms, clode_platforms and contributor type."

Anything missing from this list?

        - keywords
        - namespaces
        - names
        - tags
        - deprecated

**Comment by alikins** [comment]
@chouseknecht "Add the search parameters from Community Galaxy that apply to Collections. Exclude platforms, clode_platforms and contributor type."

For /api/v1/search/ in community galaxy, these search/filter query params appear to be:

- content_type
- namespaces
- tags
- tags_autocomplete
- keywords
- deprecated
- autocomplete
- ~~platforms~~
- ~~platforms_autocomplete~~
- ~~cloud_platforms~~
- ~~username~~
- ~~username_autocomplete~~
- ~~vendor~~

**Comment by chouseknecht** [comment]
@cutwater and @newswangerd have some changes to `_ui`. Assigning to @cutwater.

**Comment by alikins** [comment]
Based on https://github.com/ansible/galaxy-api/pull/40#issuecomment-516597757 and https://github.com/ansible/galaxy-api/pull/40#issuecomment-516775679 and
https://github.com/ansible/galaxy-api/pull/40#issuecomment-516871049

namespaces
- name (should be default)

collections
- namespace
- name

collections/{namespace}/{name}/versions/
- semver
- import date

/imports/collections/
- import task id
- import date
- success/status?

/users
- name (default)
- creation date
- last login date

/_ui/tags/
- tag name (default)

From @newswangerd via https://github.com/ansible/galaxy-api/pull/40#issuecomment-516871049

Collections:
- created date of latest version (not sure this is possible)
- download count
- best match (assuming we're using something like postgres full text search)

Namespaces:
- Company name
