### ISSUE TITLE
One-shot uploader in Pulp-Ansible

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-dev#6]
Add a callback to the one-shot uploader in `pulp-ansible` that notifies Galaxy when an import task has completed.

**Comment by chouseknecht** [comment]
Assigning @awcrosby as well so that he's aware of this work and up to speed on how it impacts the import process.

**Comment by cutwater** [comment]
Closed by ansible/galaxy-api#61 and pulp/pulp_ansible#176
