### ISSUE TITLE
API: Enable manual approval of collection version

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-dev#61]
We discussed a workflow for manually approving a new Collection Version artifact. The workflow will look like the following:

1. When a new collection version artifact is successfully imported, it will be set to an 'unapproved' state.
2. When the import completes, Automation Hub will send an email notification to the partner engineering team, alerting that a new collection version needs to be reviewed. The notification will include (if possible) a link to the import detail.
3. Someone from the partner engineering team will review the import output, and may choose to set the state to approved.

**Comment by newswangerd** [comment]
We will be adding a custom view for partner engineers to manage this. 

APIs are currently being added to support this
- Pulp: https://pulp.plan.io/issues/5579
- Automation hub: https://github.com/ansible/galaxy-dev/issues/132

Designs for this are coming soon.

**Comment by newswangerd** [comment]
Closed as duplicated of https://github.com/ansible/galaxy-dev/issues/132
