### ISSUE TITLE
UI: Enable manual approval a collection version

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-dev#62]
The workflow we discussed will look like the following:

1. When a new collection version artifact is successfully imported, it will be set to an 'unapproved' state.
2. When the import completes, Automation Hub will send an email notification to the partner engineering team, alerting that a new collection version needs to be reviewed. The notification will include (if possible) a link to the import detail.
3. Someone from the partner engineering team will review the import output, and may choose to set the state to approved.
4. The UI will present a checkbox or widget allowing the partner engineer to set the state to approved. Only partner engineers will be able to view and modify the widget.

**Comment by newswangerd** [comment]
Closed as this is a duplicated of https://github.com/ansible/galaxy-dev/issues/62

**Comment by newswangerd** [comment]
We will be adding a custom view for partner engineers to manage this.

APIs are currently being added to support this

    Pulp: https://pulp.plan.io/issues/5579
    Automation hub: #132

Designs for this are coming soon.
