### ISSUE TITLE
Query parameters for the namespace API

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy-dev#86]
- ~`tenant`: allows the UI to select namespaces that belong to a specific tenant (account number). This is used for getting a list of namespaces that the user owns.~
- `sort`: allows sorting the namespaces by name
- `keywords`: search namespaces for the given keywords. For now this can just be match on the namespace name

**Comment by alikins** [comment]
- [ ] update openapi spec to describe these params
- [ ] params implementation
  - [ ] tenant
    - [ ] query/filter by tenant/account number
        - [ ] queryset for joining across namespace owner
    - [ ] any special error handling for no matching owner/tenant?
    - [ ] any validation of tentant/account number?
  - [ ]  sort
    - [ ] by namespace name 
  - [ ] keywords
     - [ ] query/filter by matching keyword value against namespace name
     - [ ] *low priority* other fields to filter agains
       - [ ] company
       - [ ] description
       - [ ] resources txt?
       - [ ] namespacelink urls?

**Comment by alikins** [comment]
@newswangerd Is this for `/namespaces/`  or `/_ui/namespaces/`  or both?

**Comment by alikins** [comment]
@alikins ping cutwater about tenant filter before diving in to much

**Comment by newswangerd** [comment]
definitely `/_ui/namespaces/`. I don't know if these are useful for `namespaces/` or not. I'm not really the consumer of that API
