### ISSUE TITLE
Query parameters for the UI collections API

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy-dev#87]
- [x] `namespace`: get all the collections that match the EXACT namespace name given.
- [x] `keywords`: search collections
- [ ] `sort`: sort collections by name, namespace, download count, best match
- [x] `tags`: filter collections by list of tags
- [x] `deprecated`: if `true` return only deprecated collections, if `false` return only non deprecated collections, if  `null` return deprecated and non deprecated collections

**Comment by alikins** [comment]
@cutwater A few parts of this:
-  [ ] adding params to the galaxy-api `/collections` viewsets 
  - [ ] adding params etc to api spec
- [ ] then using those to build up galaxy_pulp api client method calls to hit the pulp_ansible api
- [ ] making sure the related pulp_ansible API supports those params
 - [ ] assuming goal is to implement the sorting/filtering in pulp_ansible db queries (and not in python code on galaxy-api side)

**Comment by alikins** [comment]
namespace: supporting in pulp_ansible
keywords: translate to 'q' in pulp_ansible

**Comment by alikins** [comment]
@newswangerd And this is for '/collections' endpoint correct  (https://petstore.swagger.io/?url=https://raw.githubusercontent.com/ansible/galaxy-api/master/openapi/openapi.yaml#/Collections/listCollections) ? 

Or for `/_ui/collections/` (https://petstore.swagger.io/?url=https://raw.githubusercontent.com/ansible/galaxy-api/master/openapi/openapi.yaml#/UI%3A%20Collections/listCollectionsUi) ?

Both?

**Comment by alikins** [comment]
(some links for my convience)
current galaxy-api openapi: https://petstore.swagger.io/?url=https://raw.githubusercontent.com/ansible/galaxy-api/master/openapi/openapi.yaml

current galaxy-api galaxy_pulp bindings: https://petstore.swagger.io/?url=https://raw.githubusercontent.com/ansible/galaxy-api/master/bindings/openapi.yaml#/

pulp_ansible api: https://pulp-ansible.readthedocs.io/en/latest/restapi.html

**Comment by chouseknecht** [comment]
For the AnsibleFest demo we don't expect the following to be working:

- search by tag to work
- sorting

**Comment by alikins** [comment]
@newswangerd 

> sort: sort collections by name, namespace, download count, best match

`sort` or `order`?  

community galaxy `/ui/repos-or-collections` looks like it supports 'order' but not 'sort'. 
`/ui/search` in community galaxy has 'order' and 'order_by' but not 'sort'. Did you mean `order`?

**Comment by alikins** [comment]
afaict, `namespace` query param should already work.

`GET api/automation-hub/v3/_ui/collections/?namespace=alikins` the query params dict gets passed to the galaxy_pulp api as kwargs and eventually to https://github.com/pulp/pulp_ansible/blob/master/pulp_ansible/app/galaxy/v3/views.py#L176

**Comment by newswangerd** [comment]
We are super inconsistent in galaxy, we use `order_by`, `order` and (I think in some cases) `sort`. You can pick whatever makes the most sense to you for automation hub as long as it's the same for all the endpoints.

It's been a while since I booted up the API, but I think alex fixed `namespace` shortly after I submitted this issue.

**Comment by alikins** [comment]
@newswangerd Probably doesn't matter a ton for demo, but should these query params

- Should the params support comma separated values?  ie collections/?namespace=foo,bar

- or -

- Should providing multiple params of the same type work?  ie, collections/?namespace=foo;namespace=bar
   - if each param can be provided multiple times, how should they be combined? AND'ed?

At the moment, it appears the latter is the default behavior. Does the current API usage need one approach or the other?

**Comment by newswangerd** [comment]
we did number 1 in galaxy and it's not really how you're supposed to do params. I'd like to do option 2 for automation hub.

I think AND makes the most sense. People generally add more filters to narrow down the results.

**Comment by chouseknecht** [comment]
Deferring `tags` and `sort` until after AnsibleFest

**Comment by alikins** [comment]
'sort' depends on https://pulp.plan.io/issues/5399
'tags' depends on https://pulp.plan.io/issues/5399

Both 'post fest' as mentioned in:
https://github.com/ansible/galaxy-dev/issues/87#issuecomment-527515244
https://github.com/ansible/galaxy-dev/issues/87#issuecomment-532247744

**Comment by chouseknecht** [comment]
This is mostly done. If we need to do more, we'll create a new issue.
