### ISSUE TITLE
Fix SSO token implementation

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-dev#96]
Post AnsibleFest we need to complete the following tasks for implementing SSO tokens: 

- UI: Present the JWT offline token to user with a note that the token is valid as long as it gets used every 30 days.
- UI: present a link to the token management page where the an offline token can be invalidated: ```https://sso.redhat.com/auth/realms/redhat-external/account/```
- UI: provide instructions or an example of putting the token in the config file
- API: within the response object for ```/api``` include a link to where the client should go to generate an access token (applies to Community Galaxy as well, in which case the value will be null).
- Client: check the ```/api``` response object for a token generation link. If this link exists, then generate a token.
- Client: add logic to generate an access token. Example: ```curl -X POST 'https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token' -d "grant_type=offline_token" -d "client_id=customer-portal" -d "refresh_token=<token>"```
- Client: make subsequent API requests with the correct token

**Comment by alikins** [comment]
See https://github.com/ansible/ansible/pull/63031 for ansible-galaxy changes.

And https://github.com/ansible/galaxy-api/pull/95 for galaxy-api changes.
